const express = require('express');
const line = require('@line/bot-sdk');
const axios = require('axios');
const { MongoClient } = require('mongodb');

const app = express();

const config = {
  channelAccessToken: process.env.LINE_ACCESS_TOKEN,
  channelSecret: process.env.LINE_SECRET 
};

// MongoDB Configuration
const mongoClient = new MongoClient(process.env.MONGODB_URI);
const dbName = "legalBotDB";
let db;

async function initDB() {
    try {
        await mongoClient.connect();
        db = mongoClient.db(dbName);
        console.log("Connected to MongoDB for conversation memory.");
    } catch (err) {
        console.error("MongoDB Connection Error:", err);
    }
}
initDB();

const client = new line.messagingApi.MessagingApiClient({ 
    channelAccessToken: config.channelAccessToken 
});

let userMessageCounts = {};
let lastResetDate = new Date().toLocaleDateString("en-US", { timeZone: "Asia/Bangkok" });

function checkAndResetDailyCounts() {
    const today = new Date().toLocaleDateString("en-US", { timeZone: "Asia/Bangkok" });
    if (today !== lastResetDate) {
        userMessageCounts = {};
        lastResetDate = today;
    }
}

const LANGUAGES = {
    'thai': {
        systemPrompt: "คุณคือผู้ช่วยกฎหมายไทย ตอบคำถามให้กระชับ ตรงประเด็น และเข้าใจง่ายที่สุด ใช้ภาษาที่เป็นกันเองแต่สุภาพ หากมีข้อกฎหมายที่เกี่ยวข้องให้สรุปสั้นๆ",
        limitTitle: "ครบโควตาฟรีแล้ว",
        limitText: "คุณใช้สิทธิ์ครบ 10 ข้อแล้ว สมัครสมาชิกเพื่อใช้งานต่อ",
        payButton: "สมัครสมาชิก 20 บาท",
        disclaimer: "\n\n**ข้อความปฏิเสธความรับผิดชอบ:** ข้อมูลนี้ไม่ใช่คำแนะนำทางกฎหมาย",
        ctaLabel: "ปรึกษาทนายความ"
    },
    'english': {
        systemPrompt: "You are a Thai Law Assistant. Be direct, clear, and concise. Avoid unnecessary legal jargon and provide punchy, easy-to-understand answers.",
        limitTitle: "Daily Limit Reached",
        limitText: "10 free questions used. Subscribe for unlimited access.", 
        payButton: "Subscribe 20 THB", 
        disclaimer: "\n\n**Disclaimer:** Not official legal advice.",
        ctaLabel: "Consult a Lawyer"
    },
    'chinese': {
        systemPrompt: "你是一位泰国法律助手。请提供直接、清晰且简练的回答。避免使用不必要的法律术语，确保回答易于理解。",
        limitTitle: "已达到每日上限",
        limitText: "您已达到10个问题的免费额度。请订阅。", 
        payButton: "支付 20 泰铢",
        disclaimer: "\n\n**免责声明：** 本信息不构成正式法律建议。",
        ctaLabel: "咨询律师"
    }
};

// --- CORRECTED FLEX GREETING ---
function createGreetingFlex(lang) {
    const isThai = lang === 'thai';
    const isChinese = lang === 'chinese';

    // The correct disclaimer text as requested by the user
    const bodyText = "Welcome! I'm here to help with your Thai legal queries. All answers are generated by Ai and they are not legal advice. All answers should be used as reference only. Please note that your conversation data will be collected for ease of Ai to provide the most accurate answers. All data collected will be deleted in 1 hour.";

    return {
        "type": "bubble",
        "header": {
            "type": "box",
            "layout": "vertical",
            "contents": [
                {
                    "type": "text",
                    "text": isThai ? "ผู้ช่วยกฎหมายไทย ⚖️" : (isChinese ? "泰国法律助手 ⚖️" : "Thai Law Assistant ⚖️"),
                    "weight": "bold",
                    "color": "#FFFFFF",
                    "size": "md"
                }
            ],
            "backgroundColor": "#0055AA"
        },
        "body": {
            "type": "box",
            "layout": "vertical",
            "contents": [
                {
                    "type": "text",
                    "text": bodyText,
                    "wrap": true,
                    "size": "sm",
                    "color": "#333333"
                }
            ]
        },
        "footer": {
            "type": "box",
            "layout": "vertical",
            "spacing": "sm",
            "contents": [
                {
                    "type": "button",
                    "style": "link",
                    "height": "sm",
                    "action": {
                        "type": "uri",
                        "label": "Read Policy",
                        "uri": "https://yourdomain.com/privacy"
                    }
                },
                {
                    "type": "button",
                    "style": "primary",
                    "color": "#0055AA",
                    "height": "sm",
                    "action": {
                        "type": "message",
                        "label": "I Accept",
                        "text": isThai ? "เริ่มแชท" : "Start Chat"
                    }
                }
            ]
        }
    };
}

async function handleEvent(event) {
    const userId = event.source.userId;
    const replyToken = event.replyToken;

    // 1. Handle Language Selection via Keywords
    if (event.type === 'message' && event.message.type === 'text') {
        const userText = event.message.text.trim();
        const KEYWORD_MAP = {
            'SET_LANG_TH': 'thai',
            'SET_LANG_EN': 'english',
            'SET_LANG_ZH': 'chinese'
        };

        if (KEYWORD_MAP[userText]) {
            const selectedLang = KEYWORD_MAP[userText];
            await db.collection("users").updateOne(
                { userId },
                { $set: { preferredLang: selectedLang, consented: true } },
                { upsert: true }
            );

            return await client.replyMessage({
                replyToken,
                messages: [{
                    type: "flex",
                    altText: "Legal Greeting & Consent",
                    contents: createGreetingFlex(selectedLang)
                }]
            });
        }
    }

    if (event.type !== 'message' || event.message.type !== 'text') return;

    const userText = event.message.text;
    checkAndResetDailyCounts();

    const userDoc = await db.collection("users").findOne({ userId });
    const userLang = userDoc?.preferredLang || 'english';
    const lang = LANGUAGES[userLang];

    if (!userMessageCounts[userId]) userMessageCounts[userId] = 0;
    
    if (userMessageCounts[userId] >= 10) {
        const limitMsg = {
            type: 'template',
            altText: 'Limit Reached',
            template: {
                type: 'buttons',
                title: lang.limitTitle,
                text: lang.limitText,
                actions: [{ type: 'uri', label: lang.payButton, uri: 'https://CNvTn8.short.gy/Z3S9Vo?userId=' + userId }]
            }
        };
        return await client.replyMessage({ replyToken, messages: [limitMsg] });
    }

    userMessageCounts[userId]++;
    await displayLoadingAnimation(userId);

    const callGemini = async (retries = 3) => {
        try {
            return await axios.post(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${process.env.GEMINI_API_KEY}`, {
                contents: [{ role: "user", parts: [{ text: userText }] }],
                systemInstruction: { parts: [{ text: lang.systemPrompt }] }
            });
        } catch (error) {
            if (error.response?.status === 429 && retries > 0) {
                await new Promise(r => setTimeout(r, 3000));
                return callGemini(retries - 1);
            }
            throw error;
        }
    };

    try {
        const response = await callGemini();
        const aiText = response.data.candidates?.[0]?.content?.parts?.[0]?.text || "No response.";

        const finalMessages = [
            { type: 'text', text: aiText + lang.disclaimer },
            {
                type: 'template',
                altText: 'Legal Help',
                template: {
                    type: 'buttons',
                    text: userLang === 'thai' ? 'ต้องการทนายหรือไม่?' : (userLang === 'chinese' ? '需要律師嗎？' : 'Need a lawyer?'),
                    actions: [{ type: 'uri', label: lang.ctaLabel, uri: 'https://CNvTn8.short.gy/KXzjQr' }]
                }
            }
        ];
        await client.replyMessage({ replyToken, messages: finalMessages });
    } catch (error) {
        console.error("Process Error:", error.message);
    }
}

async function displayLoadingAnimation(userId) {
    try {
        await axios.post('https://api.line.me/v2/bot/chat/loading/start', { chatId: userId, loadingSeconds: 10 }, {
            headers: { 'Authorization': `Bearer ${config.channelAccessToken}`, 'Content-Type': 'application/json' }
        });
    } catch (err) {}
}

app.post('/webhook', line.middleware(config), (req, res) => {
    res.status(200).send('OK'); 
    req.body.events.forEach(handleEvent);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Running on ${PORT}`));